//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsDev.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsDev.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Attachment.
        /// </summary>
        public static string AddAttachmentButton {
            get {
                return ResourceManager.GetString("AddAttachmentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedAt.
        /// </summary>
        public static string DataGrid_CreatedAt {
            get {
                return ResourceManager.GetString("DataGrid_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeadLine.
        /// </summary>
        public static string DataGrid_DeadLine {
            get {
                return ResourceManager.GetString("DataGrid_DeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DataGrid_Description {
            get {
                return ResourceManager.GetString("DataGrid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string DataGrid_Id {
            get {
                return ResourceManager.GetString("DataGrid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DataGrid_Name {
            get {
                return ResourceManager.GetString("DataGrid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to TaskManager?.
        /// </summary>
        public static string LoginWindow_new {
            get {
                return ResourceManager.GetString("LoginWindow_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string PostCommentButton {
            get {
                return ResourceManager.GetString("PostCommentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string RegistrationWindow_already {
            get {
                return ResourceManager.GetString("RegistrationWindow_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string TabControl_Projects {
            get {
                return ResourceManager.GetString("TabControl_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TabControl_Settings {
            get {
                return ResourceManager.GetString("TabControl_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string TaskAttachments {
            get {
                return ResourceManager.GetString("TaskAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string TaskComments {
            get {
                return ResourceManager.GetString("TaskComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedAt.
        /// </summary>
        public static string TaskCreatedAt {
            get {
                return ResourceManager.GetString("TaskCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string TaskPriority {
            get {
                return ResourceManager.GetString("TaskPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string TaskProgress {
            get {
                return ResourceManager.GetString("TaskProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TaskStatus {
            get {
                return ResourceManager.GetString("TaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
    }
}
